// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxvrnukyoyfcijzpmvaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4dnJudWt5b3lmY2lqenBtdmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzAwMzcsImV4cCI6MjA3MTIwNjAzN30.1BmjllcAqFZl5AnVGkIHZ5nhJm_yYV70Q7BDA2uBCl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});